on:
  push:
    branches:
      - main

jobs:
  job_main:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/230200288570/locations/global/workloadIdentityPools/github-actions-deploy/providers/github-actions'
        service_account: 'github-actions@buriburibot.iam.gserviceaccount.com'

    - id: 'ssh'
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: 'instance-1'
        zone: 'us-west1-b'
        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        command: |
          sudo docker stop $(docker ps -q)
          sudo docker system prune -f
          sudo docker rmi main_image
          sudo git -C ../kabaodao/BuriBuriBot pull origin main
          sudo docker build -t main_image ../kabaodao/BuriBuriBot/.
          sudo docker run -d -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} main_image

    - name: 'Show Output'
      run: |-
        echo '${{ steps.ssh.outputs.stdout }}'
        echo '${{ steps.ssh.outputs.stderr }}'
